version: '3.3'
services:
  todo:
    build:
      context: .
    depends_on:
      - mysqlserver
    ports:
      - 8000:8000
      - 8080:8080
    environment:
      - SERVER_PORT=8080
      - MYSQL_URL=jdbc:mysql://mysqlserver/todo?createDatabaseIfNotExist=true
      - MYSQL_USER=todo
      - MYSQL_PASS=todo
    volumes:
      - ./:/app
    command: ./mvnw spring-boot:run -Dspring-boot.run.profiles=mysql -Dspring-boot.run.jvmArguments="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8000"

  mysqlserver:
    image: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=todo
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=todo
      - MYSQL_PASSWORD=todo
      - MYSQL_DATABASE=todo
    volumes:
      - mysql_data:/var/lib/mysql
      - mysql_config:/etc/mysql/conf.d
volumes:
  mysql_data:
  mysql_config:

